[package]
name = "clash-proxy-provider"
version = "0.1.2"
authors = ["ibigbug <i@xiaoba.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.1.1"

reqwest = { version = "0.10" }
tokio = { version = "0.2", features = ["full"] }

serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
